version: "1"
rootDirectory: "./"
substitutes: []
template: "template.mol2"

jobs:
- name: right_substitute
  use: add_substitutent
  with:
    entry: P11
    centers:
    - H33
    - H36
    substitutes:
    - H
    - name: Me
      substitute: CH3
    - CH2F
    - CHF2
    - CF3
- name: right_substitute
  use: add_subsitutent
  with:
    entry: P12
    centers:
    - H34
    - H35
    substitutes: all
- name: output_A1
  use: output
  with:
    pattern: "{right_substitute}.{left_subsititute}/A1.mol2"
- name: add_hydrogen
  use: import
  with:
    targets: 
    - path: hydrogens.mol2
      rotation:
        axis: [0, 0, 1]
        center: [0, 0, 0]
        angle: 120
      translation: no
- name: connect_Hs_to_cata
  use: modify_bond
  with:
    connect:
    - [HLeft, Mn1, 1]
    - [HRight, N1, 1]
- name: output_A2
  use: output
  with:
    pattern: "{right_substitute}.{left_subsitute}/A2.mol2"
- name: add_substrate
  use: import
  with:
    targets:
    - name: acetone
      path: substrate/acetone.mol2
      rotation: no
      translation: no
    - name: amine
      path: substrate/amine.mol2
      rotation: no
      translation: no
- name: output_A3
  use: output
  with:
    pattern: "{right_substitute}.{left_substitute}/A3_{add_substrate}.mol2"
- name: generate_A4
  use: modify_bond
  with:
    connect:
    - [HLeft, R1, 1]
    - [HRigth, R2, 1]
    disconnect:
    - [HLeft, Mn1]
    - [HRight, N2]
- name: output_A4
  use: output
  with:
    pattern: "{right_substitute}.{left_substitute}/A4_{add_substrate}.mol2"